#!/usr/bin/env bash
# configures an Ubuntu machine with nginx
FILE="/etc/nginx/sites-available/default"

REDIRECT="\n\tlocation /redirect_me {\n\t\treturn 301 https://youtu.be/dQw4w9WgXcQ;\n\t}\n"
ERRORREDIRECT="\n\terror_page 404 /404error.html;\n\tlocation = /404error.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}\n"
CUSTOMHEADER='\n\tadd_header X-Served-By $hostname;\n'


sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee -a /var/www/html/index.nginx-debian.html
sudo sed -i "37i\ $REDIRECT" "$FILE"

echo 'Ceci n'\''est pas une page' | sudo tee -a /usr/share/nginx/html/404error.html
sudo sed -i "37i\ $ERRORREDIRECT" "$FILE"

sudo sed -i "37i\ $CUSTOMHEADER" "$FILE"
sudo service nginx restart
